# Site wide configuration

title: JS-Outdoors
description: Hunting and Fishing Stories and Reviews from the Midwest
logo: bio-photo.jpg
# teaser: 400x250 px
locale: en
url:

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist


# Octopress configuration

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: article

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name:
  email:
  twitter: jasonswingen
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg
  disqus-shortname: jasonswingen


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
