# Site wide configuration

title: JS-Outdoors
description: Hunting and Fishing Stories from the Midwest
logo: JS_OUTDOORS_logo.jpg
teaser: teaser.jpg
locale: en
url: js-outdoors.com
user.email: jason.swingen@gmail.com
user.name: JasonSwingen

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist


# Octopress configuration

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: article

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Jason Swingen
  email: jason.swingen@gmail.com
  web: http://www.jasonswingen.com
  twitter: jasonswingen
  instagram: jasonswingen
  googleplus: JasonSwingen
  google:
    ad-client: "ca-pub-2944231685290718"
    ad-slot: "6324043781"
  bio: Jason is a Front-End Web Developer and Internet Marketer with a passion for all things outdoors. Follow Jason on <a target="_blank" href="https://www.instagram.com/jasonswingen/">Instagram</a>, <a target="_blank" href="https://twitter.com/jasonswingen">Twitter</a>, and <a target="_blank" href="https://plus.google.com/+JasonSwingen">Google+</a> to stay updated on new content.
  avatar: bio-photo.jpg
  disqus-shortname: jasonswingen


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
