# Site wide configuration

title: JS-Outdoors
description: Hunting and Fishing Stories from the Midwest
logo: JS_OUTDOORS_logo.jpg
teaser: teaser.jpg
locale: en
url:
user.email: jason.swingen@gmail.com
user.name: JasonSwingen

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist


# Octopress configuration

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: article

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Jason Swingen
  email: jason.swingen@gmail.com
  web: https://jasonswingen.com/
  twitter: jasonswingen
  instagram: jasonswingen
  google:
    ad-client: "ca-pub-2944231685290718"
    ad-slot: "6324043781"
  bio: Hi! I'm Jason. I'm an outdoor writer, fly tier/fisherman, and big game hunter based out of Duluth, MN. You can learn more <a href="/about.html">about me</a>, or follow me below to keep updated!
  avatar: bio-photo.jpg
  disqus-shortname: jasonswingen


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
